application: kifushare
version: 1
runtime: python
api_version: 1

handlers:
- url: /Kifu.swf
  static_files: Kifu.swf
  upload: Kifu.swf
- url: /stylesheets
  static_dir: stylesheets
- url: /kifudir
  static_dir: kifudir
  mime_type: text/plain
- url: /js
  static_dir: js
- url: .*
  script: main.py
